### ISSUE TITLE
[Feature request] Add a timeout on complete to redirect back.

### ISSUE THREAD

**Issue by lewisjb** [UQComputingSociety/signup#1]
Currently you have to manually click "go back", which is fine if you do it at home. But on market day there are a lot of people, so it would be nice if it did it automatically after a short delay.

There are other possible solutions to this, like changing the "thankyou" page to just insert it at the top of the sign-up form, and clear the field.

**Comment by TRManderson** [comment]
Done: https://github.com/UQComputingSociety/signup/commit/900a335d13b93d10e0dc900afbbc90a71616dfa1
