### ISSUE TITLE
Setting Dr. Joel's `memberhsip_type` column to 'life' can break things.

### ISSUE THREAD

**Issue by bradleysigma** [UQComputingSociety/signup#17]

**Comment by katrinafyi** [comment]
What things break? It may be because the model doesn't expect that value.

**Comment by nicklambourne** [comment]
We'll need to create a new membership subtype in models.py.

**Comment by bradleysigma** [comment]
`join.uqcs.org.au/admin/list` gives an `Internal Server Error` when a `membership_type` is set to `life`.

**Comment by katrinafyi** [comment]
Fixed in #39.
