### ISSUE TITLE
Redesign for consistency

### ISSUE THREAD

**Issue by draganmarjanovic** [UQComputingSociety/signup#3]
This needs to be redesigned for consistency with our website and Slack signup form.

Something such as [slack.uqcs.org.au](http://slack.uqcs.org.au) would be ideal.

![image](https://cloud.githubusercontent.com/assets/914767/24245069/1e7cb388-100d-11e7-83a2-9d15a17c221d.png)

**Comment by lewisjb** [comment]
@somebody1234

**Comment by somebody1234** [comment]
@lewisjb Oh yeah sorry, kinda forgot about this, will start on it again asap
