### ISSUE TITLE
More inclusive gender options

### ISSUE THREAD

**Issue by katrinafyi** [UQComputingSociety/signup#40]
Currently, there is only male, female, and other/unspecified which is not great. Moreover, the other option is indistinguishable from the unspecified option (both are stored as null).

We should at least add non-binary as an option and distinguish other and unspecified. Allowing free text under the other option would be nice but could complicate aggregate statistics.

**Comment by bradleysigma** [comment]
One solution would be to have the current "Male", "Female" & "Other / Unspecified" buttons, but clicking the latter summons a free text input. In the database, there would be a field for the buttons (storing `M`/`F`/`O`/`null`), and a different field for free text input. As such, basic aggregate statistics can be obtained from the first field, while additional statistics can manually be extracted from the second as required.

**Comment by ndrwbrwn** [comment]
Closing this as the mentioned PR seems to have solved the issue?
